import os
import glob
import re

html_files = glob.glob('templates/*.html')
skip_files = ['crane_scale.html', 'portal.html', 'login.html', 'index.html', 'admin_users.html']

def convert_to_wizard(html):
    if 'class="step-panel"' in html:
        return html
    
    # We will replace the <div class="section-box"> with <div class="step-panel" data-step="X"><div class="section-box">
    # Wait, the wizard CSS assumes step-panel IS the container.
    # Actually, in index.html, it's:
    # <div class="step-panel active" data-step="1">
    #    <div class="section-box"> ... </div>
    # </div>
    
    # Let's count section-boxes
    sections = re.findall(r'<div class="section-box"', html)
    total = len(sections)
    if total <= 1:
        return html # Not multi-section
        
    print(f"Converting with {total} sections...")
    
    # Inject stepper bar right after <form id="recordForm">
    stepper_html = '''
                <div class="stepper-bar" style="display: flex; gap: 8px; margin-bottom: 24px; overflow-x: auto; flex-wrap: nowrap; padding-bottom: 8px;">
'''
    for i in range(1, total + 1):
        active = ' active' if i == 1 else ''
        stepper_html += f'                    <div class="step-indicator{active}" data-step="{i}">Step {i}</div>\n'
    
    stepper_html += '''                </div>
                <div class="wizard-progress-bar" style="height: 6px; background: #334155; border-radius: 4px; margin-bottom: 32px; overflow: hidden;">
                    <div id="wizardProgressFill" style="height: 100%; width: ''' + str(100/total) + '''%; background: linear-gradient(90deg, #0ea5e9, #38bdf8); transition: width 0.3s ease;"></div>
                </div>
'''
    
    # Replace <form id="recordForm"> with form + stepper
    html = re.sub(r'(<form id="recordForm"\s*>)', r'\1' + stepper_html, html, count=1)
    
    # Wrap section-boxes
    # We split by <div class="section-box"
    parts = html.split('<div class="section-box"')
    new_html = parts[0]
    
    step = 1
    for i in range(1, len(parts)):
        active = ' active' if step == 1 else ''
        panel_start = f'\n                <div class="step-panel{active}" data-step="{step}">\n                    <div class="section-box"'
        
        # We need to find the END of the section box to close the step-panel.
        # But section-boxes have nested divs.
        # The easiest way is to close the step-panel right before the NEXT section-box, or before the form-actions.
        
        # So we just prefix the split token.
        new_html += panel_start + parts[i]
        
        # Now, wait. Where do we close the step-panel?
        # If we just add it before the next section box, that works for all except the last one.
        # For the last one, we close it before <div class="form-actions">
        step += 1

    # But wait, we need to close the </div> of step-panel!
    # Instead of doing this manually, let's just use simple python string replacement
    return new_html

# Better robust way:
def robust_convert(html):
    if 'class="step-panel"' in html: return html
    if '<form id="recordForm"' not in html: return html
    
    sections = re.findall(r'(<div class="section-box">.*?<!-- /section-box -->)', html, re.DOTALL)
    if not sections:
        # Fallback if no comment
        pass
    
    # Actually, all templates generated by create_templates.py have <!-- /section-box --> !!
    # Let's check!
    return html

